version: '3.8'
services:
  server:
    secrets:
      - firebase_service_account
    environment:
      - FIREBASE_SERVICE_ACCOUNT_B64_FILE=/run/secrets/firebase_service_account
secrets:
  firebase_service_account:
    file: ./secrets/firebase_service_account.b64
