version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    env_file: ./backend/.env
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
